"""Type stubs for slack_sdk."""

from typing import Any

class WebClient:
    """Synchronous Slack Web API client."""

    def __init__(self, token: str | None = None, **kwargs: Any) -> None: ...
    def conversations_history(self, **kwargs: Any) -> Any: ...
    def conversations_replies(self, **kwargs: Any) -> Any: ...
    def users_info(self, **kwargs: Any) -> Any: ...
